FROM ubuntu:jammy

WORKDIR /root

RUN apt-get update

RUN apt-get install -y clang libbfd-dev uthash-dev libelf-dev libcapstone-dev  libreadline-dev libiberty-dev libgsl-dev build-essential git debootstrap file cargo openssh-server apache2 nginx gcc

# Download and add Google's signing key
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

# Add Google's repository
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

# Update package list
RUN apt update

# Install Chrome
RUN apt install -y google-chrome-stable

# Build wcc & install it
RUN git clone https://github.com/endrazine/wcc.git && cd wcc && git checkout v0.0.11 && git submodule init && git submodule update && make && make install

# Build openssl 
RUN git clone https://github.com/openssl/openssl.git || echo ok
RUN cd openssl && git checkout openssl-3.0.6
RUN cd openssl && mkdir -p build-3.0.6
RUN cd openssl/build-3.0.6 && ../Configure && make

RUN cd openssl && git checkout openssl-3.0.7
RUN cd openssl && mkdir -p build-3.0.7
RUN cd openssl/build-3.0.7 && ../Configure && make

RUN cd openssl && git checkout openssl-3.0.8
RUN cd openssl && mkdir -p build-3.0.8
RUN cd openssl/build-3.0.8 && ../Configure && make

RUN apt-get install -y libbpf0 libdbus-1-3 libdevmapper1.02.1 libdns-export1110 libestr0 libglib2.0-0 libglib2.0-dev libkmod2 libmnl0 libnewt0.52 libpopt0 sudo systemd libxtables12 libfastjson-dev

# Prepare wcc tests
RUN git clone https://github.com/endrazine/wcc-tests.git && cd wcc-tests && make

WORKDIR /root/wcc-tests
