#!/bin/bash

find `echo $PATH|tr ":" " "` -type f -exec file '{}' \; 2>/dev/null|grep -w ELF |grep dynamically|grep executable|awk -F ":" '{print $1}'|while read testbin
do
	echo "-- ${testbin}"
	cp "${testbin}" ./testbin
	wld --libify --no-init ./testbin	
	LD_PRELOAD="/usr/lib64/libcrypt.so.2.0.0:/usr/lib64/libgpg-error.so.0:/usr/lib64/libassuan.so.0:/usr/lib64/libpython3.13.so.1.0:/usr/lib64/libsystemd.so.0:/usr/lib64/libstdc++.so.6:/usr/lib64/libgcc_s.so.1:/usr/lib64/libgnutls.so.30:/usr/lib64/libwget.so.3:/lib64/librustc_driver-0f3bac3fbc6a3b6e.so" ./loader ./testbin
done |tee -a exec.log
