#!/bin/bash

find `echo $PATH|tr ":" " "` -type f -exec file '{}' \; 2>/dev/null|grep -w ELF |grep dynamically|grep executable|awk -F ":" '{print $1}'|while read testbin
do
	echo "-- ${testbin}"
	cp "${testbin}" ./testbin
	wld --libify --no-init ./testbin
	LD_PRELOAD="/usr/lib64/libgcrypt.so.20:/usr/lib64/libgpg-error.so.0:/usr/lib64/libassuan.so.0:/usr/lib64/libpython3.12.so.1.0:/usr/lib64/libsystemd.so.0:/usr/lib64/libstdc++.so.6:/usr/lib64/libgcc_s.so.1:/lib64/libgnutls.so.30" ./loader ./testbin
done |tee -a exec.log
